### PR TITLE
Switch to lazy list. Put repaintboundary around videoplayer

### PR DESCRIPTION
**Pull request by ferhatb**
General performance improvements/repaint improvements.

### CODE REVIEW

**Comment by ferhatb** [comment]
/cc @searchy2 , did a small update that makes scrolling both on desktop and my mobile device much faster.

We'll keep on looking for ways to speed this up so it makes an even better demo of responsive framework :)

**Comment by rayliverified** [comment]
Thanks for taking the time to submit a PR and doing some performance investigation @ferhatb

**Comment by rayliverified** [comment]
One weird bug is that the Responsive Constraints are now broken.

**Comment by rayliverified** [comment]
Fixed and updated.

**Pull request merged**
